name: Auto Update VPN Subscriptions

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# ДАЕМ КЛЮЧЕВЫЕ ПРАВА НА ЗАПИСЬ ДЛЯ БОТА ПРЯМО ЗДЕСЬ
permissions:
  contents: write

jobs:
  update-subs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Proxy Parser
      run: python parser67.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add sub.txt
        if git diff --staged --quiet; then
          echo "Изменений нет. Пропускаем коммит."
        else
          git commit -m "Ежечасное автоматическое обновление конфигов [GitHub Actions]"
          git push
        fi
